# Generated by Django 5.1.3 on 2024-11-21 15:37

import diary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_diary_image_url_1_diary_image_url_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='image_url_1',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='image_url_2',
        ),
        migrations.RemoveField(
            model_name='diary',
            name='image_url_3',
        ),
        migrations.AddField(
            model_name='diary',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to=diary.models.upload_to),
        ),
        migrations.AddField(
            model_name='diary',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to=diary.models.upload_to),
        ),
        migrations.AddField(
            model_name='diary',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to=diary.models.upload_to),
        ),
    ]
